resources:
- ui-deployment.yaml
- ui-service.yaml
- ui-route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: infyartifactory.jfrog.io/ccdsdam-ocp/vote-ui
  newName: infyartifactory.jfrog.io/ccdsdam-ocp/vote-ui
  newTag: "1.0"
